name: Build Ladybird Multi-Platform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_preset:
        description: 'Build preset to use (e.g., default, Debug)'
        required: true
        default: 'default'

jobs:
  build:
    name: Build Ladybird on ${{ matrix.os_display_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_type: macos
            os_runner: macos-latest # GitHub's macOS runners are typically arm64 (Apple Silicon) now
            os_display_name: "macOS (Homebrew Clang 19)"
            artifact_name_suffix: "macOS-HBClang19"
            llvm_package: "llvm@19"
          - os_type: linux
            os_runner: ubuntu-latest
            os_display_name: "Linux (Ubuntu Clang 17)"
            clang_version: "17"
            artifact_name_suffix: "Linux-Clang17"

    env:
      BUILD_PRESET_NAME: ${{ github.event.inputs.build_preset || 'default' }}
      LADYBIRD_CHECKOUT_DIR: 'ladybird_source'

    runs-on: ${{ matrix.os_runner }}

    steps:
      - name: Checkout Ladybird Browser repository
        uses: actions/checkout@v4
        with:
          repository: 'LadybirdBrowser/ladybird'
          path: ${{ env.LADYBIRD_CHECKOUT_DIR }}
          fetch-depth: 0

      - name: Set up dynamic environment variables and cache paths
        id: set-env-vars
        run: |
          VCPKG_DOWNLOADS_PATH="${{ runner.temp }}/vcpkg-downloads"
          echo "Setting VCPKG_DOWNLOADS=${VCPKG_DOWNLOADS_PATH}"
          echo "VCPKG_DOWNLOADS_DIR=${VCPKG_DOWNLOADS_PATH}" >> $GITHUB_OUTPUT
          echo "VCPKG_DOWNLOADS=${VCPKG_DOWNLOADS_PATH}" >> $GITHUB_ENV
          echo "Ensuring vcpkg downloads directory exists: ${VCPKG_DOWNLOADS_PATH}"
          mkdir -p "${VCPKG_DOWNLOADS_PATH}"
          if [ -d "${VCPKG_DOWNLOADS_PATH}" ]; then
            echo "Verified directory exists: ${VCPKG_DOWNLOADS_PATH}"
          else
            echo "Error: Failed to create directory: ${VCPKG_DOWNLOADS_PATH}"; exit 1
          fi

      - name: Cache vcpkg downloads
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-env-vars.outputs.VCPKG_DOWNLOADS_DIR }}
          key: ${{ runner.os }}-vcpkg-downloads-${{ hashFiles(format('{0}/vcpkg.json', env.LADYBIRD_CHECKOUT_DIR), format('{0}/Toolchain/CMakeLists.txt', env.LADYBIRD_CHECKOUT_DIR)) }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-downloads-

      # macOS Specific Setup
      - name: Setup Homebrew Environment (macOS)
        if: matrix.os_type == 'macos'
        run: |
          echo "Ensuring Homebrew is available and its bin directory is in PATH..."
          which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # Add Homebrew's main bin directory to GITHUB_PATH
          # brew shellenv might be another way, but this is explicit for GITHUB_PATH
          BREW_PREFIX_BIN=""
          if [ -x "/opt/homebrew/bin/brew" ]; then # Apple Silicon
            BREW_PREFIX_BIN="/opt/homebrew/bin"
          elif [ -x "/usr/local/bin/brew" ]; then # Intel
            BREW_PREFIX_BIN="/usr/local/bin"
          fi
          if [ -n "$BREW_PREFIX_BIN" ]; then
            echo "$BREW_PREFIX_BIN" >> $GITHUB_PATH
            echo "Homebrew bin directory ($BREW_PREFIX_BIN) added to PATH."
          else
            echo "Warning: Could not determine Homebrew bin directory."
          fi
          which brew || (echo "Error: Homebrew not found in PATH after setup attempt." && exit 1)

      - name: Install macOS dependencies and Setup Compiler (Homebrew ${{ matrix.llvm_package }})
        if: matrix.os_type == 'macos'
        id: setup-macos-compiler # This step now sets the compiler paths as outputs
        env:
          LLVM_PACKAGE_NAME: ${{ matrix.llvm_package }}
        run: |
          brew update --quiet
          # As per BuildInstructionsLadybird.md for macOS
          echo "Installing macOS dependencies: autoconf autoconf-archive automake ccache cmake nasm ninja pkg-config $LLVM_PACKAGE_NAME"
          brew install autoconf autoconf-archive automake ccache cmake nasm ninja pkg-config "$LLVM_PACKAGE_NAME"
          
          echo "--- Verifying installed tools ---"
          cmake --version
          ninja --version

          # Determine and export Homebrew Clang paths AFTER installation
          BREW_LLVM_PREFIX=$(brew --prefix "$LLVM_PACKAGE_NAME")
          if [ -z "$BREW_LLVM_PREFIX" ] || [ ! -d "$BREW_LLVM_PREFIX/bin" ]; then
            echo "Error: Could not find bin directory for $LLVM_PACKAGE_NAME using 'brew --prefix $LLVM_PACKAGE_NAME' (path: $BREW_LLVM_PREFIX)."
            echo "Attempting to locate llvm installation directory..."
            ls -lhd /opt/homebrew/opt/"$LLVM_PACKAGE_NAME" || ls -lhd /usr/local/opt/"$LLVM_PACKAGE_NAME"
            exit 1
          fi

          HB_CLANG="$BREW_LLVM_PREFIX/bin/clang"
          HB_CLANG_PLUS_PLUS="$BREW_LLVM_PREFIX/bin/clang++"

          if [ ! -x "$HB_CLANG" ] || [ ! -x "$HB_CLANG_PLUS_PLUS" ]; then
            echo "Error: Homebrew Clang ($HB_CLANG) or Clang++ ($HB_CLANG_PLUS_PLUS) not found or not executable in $BREW_LLVM_PREFIX/bin."
            ls -l "$BREW_LLVM_PREFIX/bin/"
            exit 1
          fi
          
          echo "Found Homebrew Clang: $HB_CLANG"
          "$HB_CLANG" --version
          echo "Found Homebrew Clang++: $HB_CLANG_PLUS_PLUS"
          "$HB_CLANG_PLUS_PLUS" --version

          echo "Adding $BREW_LLVM_PREFIX/bin to GITHUB_PATH to make it available for subsequent steps if needed directly."
          echo "$BREW_LLVM_PREFIX/bin" >> $GITHUB_PATH
          
          echo "cc_path=$HB_CLANG" >> $GITHUB_OUTPUT
          echo "cxx_path=$HB_CLANG_PLUS_PLUS" >> $GITHUB_OUTPUT

      - name: Select and Verify Xcode version (macOS - Informational)
        if: matrix.os_type == 'macos'
        run: |
          echo "--- Xcode Information (Informational) ---"
          echo "Available Xcode versions on runner:"
          ls /Applications | grep Xcode || echo "No Xcode installations found"
          CURRENT_XCODE_PATH=$(xcode-select -p)
          echo "Currently selected Xcode path: $CURRENT_XCODE_PATH"
          xcodebuild -version
          echo "System Clang version (for comparison, should NOT be used by build):"
          # Check common system clang paths if 'which clang' might point to homebrew due to PATH modification
          if [ -x "/usr/bin/clang" ]; then /usr/bin/clang --version; else echo "/usr/bin/clang not found"; fi

      # Linux Specific Setup
      - name: Setup Environment (Linux - Clang ${{ matrix.clang_version }})
        if: matrix.os_type == 'linux'
        id: setup-env-linux
        run: |
          echo "cc_path=/usr/bin/clang-${{ matrix.clang_version }}" >> $GITHUB_OUTPUT
          echo "cxx_path=/usr/bin/clang++-${{ matrix.clang_version }}" >> $GITHUB_OUTPUT

      - name: Install Linux dependencies and required tool versions (Clang ${{ matrix.clang_version }})
        if: matrix.os_type == 'linux'
        env:
          DEBIAN_FRONTEND: noninteractive
          CLANG_VERSION_TO_INSTALL: ${{ matrix.clang_version }}
          CMAKE_REQUIRED_VERSION: "3.25"
        run: |
          sudo apt-get update -y -q
          sudo apt-get install -y -q --no-install-recommends \
            wget gpg ca-certificates software-properties-common coreutils apt-utils curl

          INSTALLED_CMAKE_VERSION=$(cmake --version 2>/dev/null | head -n1 | sed 's/cmake version //g' || echo "0.0.0")
          echo "Initial CMake version: $INSTALLED_CMAKE_VERSION"
          if ! dpkg --compare-versions "$INSTALLED_CMAKE_VERSION" "ge" "$CMAKE_REQUIRED_VERSION"; then
            echo "CMake version $INSTALLED_CMAKE_VERSION is less than required $CMAKE_REQUIRED_VERSION. Installing from Kitware apt repository."
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/kitware.list > /dev/null
            sudo apt-get update -y -q
            sudo apt-get remove --purge -y cmake # Remove old version first
            sudo apt-get install -y -q --no-install-recommends cmake
          else
            echo "CMake version $INSTALLED_CMAKE_VERSION is satisfactory."
          fi
          echo "Final CMake version:"; cmake --version

          sudo wget -O /usr/share/keyrings/llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
          CODENAME=$(lsb_release -sc)
          LLVM_APT_LINE="deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg.key] http://apt.llvm.org/$CODENAME/ llvm-toolchain-$CODENAME-$CLANG_VERSION_TO_INSTALL main"
          echo "$LLVM_APT_LINE" | sudo tee "/etc/apt/sources.list.d/llvm-toolchain-$CODENAME-$CLANG_VERSION_TO_INSTALL.list" > /dev/null
          sudo apt-get update -y -q
          sudo apt-get install -y -q --no-install-recommends \
            clang-$CLANG_VERSION_TO_INSTALL \
            clangd-$CLANG_VERSION_TO_INSTALL \
            clang-tools-$CLANG_VERSION_TO_INSTALL \
            clang-format-$CLANG_VERSION_TO_INSTALL \
            clang-tidy-$CLANG_VERSION_TO_INSTALL \
            lld-$CLANG_VERSION_TO_INSTALL

          sudo apt-get install -y -q --no-install-recommends \
            autoconf autoconf-archive automake build-essential ccache \
            fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config \
            qt6-base-dev qt6-tools-dev-tools qt6-wayland \
            tar unzip zip \
            libpulse-dev
          echo "Clang version used:"; /usr/bin/clang-$CLANG_VERSION_TO_INSTALL --version
          echo "Ninja version:"; ninja --version

      # Common Build Step
      - name: Configure and Build Ladybird
        id: build-ladybird
        env:
          BUILD_PRESET: ${{ env.BUILD_PRESET_NAME }}
        working-directory: ./${{ env.LADYBIRD_CHECKOUT_DIR }}
        run: |
          CURRENT_OS_TYPE="${{ matrix.os_type }}"
          if [ "$CURRENT_OS_TYPE" = "macos" ]; then
            export CC="${{ steps.setup-macos-compiler.outputs.cc_path }}"
            export CXX="${{ steps.setup-macos-compiler.outputs.cxx_path }}"
            # Verification
            if [ -z "$CC" ] || [ -z "$CXX" ]; then
              echo "Error: CC or CXX is not set for macOS."
              echo "CC: $CC"
              echo "CXX: $CXX"
              exit 1
            fi
            EXPECTED_LLVM_PREFIX=$(brew --prefix "${{ matrix.llvm_package }}")
            if [[ "$CC" != "$EXPECTED_LLVM_PREFIX/bin/clang" ]]; then
              echo "Error: CC ($CC) is not pointing to the expected Homebrew Clang path ($EXPECTED_LLVM_PREFIX/bin/clang)."
              exit 1
            fi
            if [[ "$CXX" != "$EXPECTED_LLVM_PREFIX/bin/clang++" ]]; then
              echo "Error: CXX ($CXX) is not pointing to the expected Homebrew Clang++ path ($EXPECTED_LLVM_PREFIX/bin/clang++)."
              exit 1
            fi
          elif [ "$CURRENT_OS_TYPE" = "linux" ]; then
            export CC="${{ steps.setup-env-linux.outputs.cc_path }}"
            export CXX="${{ steps.setup-env-linux.outputs.cxx_path }}"
          else
            echo "Error: Unknown OS type for compiler setup: $CURRENT_OS_TYPE"; exit 1
          fi

          echo "--- Current Directory ---"; pwd
          echo "--- Ladybird Script Location ---"; ls -la Meta/ladybird.sh
          echo "--- Compiler Information ---"
          echo "Using CC: $CC"
          $CC --version || { echo "Error: Failed to get CC version. CC might be invalid or not found."; exit 1; }
          echo "Using CXX: $CXX"
          $CXX --version || { echo "Error: Failed to get CXX version. CXX might be invalid or not found."; exit 1; }
          echo "--- CMake Version ---"
          cmake --version
          echo "--- Ninja Version ---"
          ninja --version
          echo "--- Build Configuration ---"
          echo "Using BUILD_PRESET: $BUILD_PRESET"
          echo "Verifying VCPKG_DOWNLOADS env var before build: $VCPKG_DOWNLOADS"

          if [ -z "$VCPKG_DOWNLOADS" ] || [ ! -d "$VCPKG_DOWNLOADS" ]; then
             echo "Error: VCPKG_DOWNLOADS ('$VCPKG_DOWNLOADS') is not set or not a directory."; exit 1
          fi
          echo "Permissions for $VCPKG_DOWNLOADS:"; ls -ld "$VCPKG_DOWNLOADS"

          echo "--- Starting Ladybird Build ---"
          # The ladybird.sh script should respect CC and CXX environment variables for CMake.
          ./Meta/ladybird.sh build ladybird
          echo "--- Build Finished ---"
          
          ACTUAL_BUILD_SUBDIR="$BUILD_PRESET"
          if [ "$BUILD_PRESET" = "default" ]; then
            if [ -d "Build/release" ]; then
              ACTUAL_BUILD_SUBDIR="release"
            elif [ -d "Build/debug" ]; then
               ACTUAL_BUILD_SUBDIR="debug"
            elif [ ! -d "Build/default" ]; then
               echo "Warning: Neither Build/release, Build/debug, nor Build/default found for default preset. Using '$BUILD_PRESET'."
            fi
          fi

          if [ ! -d "Build/$ACTUAL_BUILD_SUBDIR" ]; then
            echo "Error: Build output subdirectory 'Build/$ACTUAL_BUILD_SUBDIR' not found!"
            echo "Listing Build directory contents:"; ls -la Build; exit 1
          fi
          
          ARTIFACT_FILE_PATH=""
          if [ "$CURRENT_OS_TYPE" = "macos" ]; then
            ARTIFACT_FILE_PATH="Build/$ACTUAL_BUILD_SUBDIR/bin/Ladybird.app"
          elif [ "$CURRENT_OS_TYPE" = "linux" ]; then
            ARTIFACT_FILE_PATH="Build/$ACTUAL_BUILD_SUBDIR/bin/Ladybird" 
          fi
          # Output for artifact upload path
          echo "artifact_sub_path=$ARTIFACT_FILE_PATH" >> $GITHUB_OUTPUT
          # Output for build log path
          echo "ACTUAL_BUILD_SUBDIR_FOR_LOGS=$ACTUAL_BUILD_SUBDIR" >> $GITHUB_OUTPUT
          echo "Artifact path determined for upload: ./${{ env.LADYBIRD_CHECKOUT_DIR }}/$ARTIFACT_FILE_PATH"

      - name: Upload Ladybird Artifact
        if: success() && steps.build-ladybird.outputs.artifact_sub_path != ''
        uses: actions/upload-artifact@v4
        with:
          name: Ladybird-${{ matrix.artifact_name_suffix }}-${{ env.BUILD_PRESET_NAME }}
          path: ${{ env.LADYBIRD_CHECKOUT_DIR }}/${{ steps.build-ladybird.outputs.artifact_sub_path }}
          if-no-files-found: error
          retention-days: 7

      - name: Upload Build Logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-build-logs-${{ matrix.artifact_name_suffix }}-${{ env.BUILD_PRESET_NAME }}
          path: |
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/${{ steps.build-ladybird.outputs.ACTUAL_BUILD_SUBDIR_FOR_LOGS }}/**/*.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/${{ steps.build-ladybird.outputs.ACTUAL_BUILD_SUBDIR_FOR_LOGS }}/vcpkg-manifest-install.log
            # Fallback paths if ACTUAL_BUILD_SUBDIR_FOR_LOGS wasn't set or was unexpected
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/${{ env.BUILD_PRESET_NAME }}/**/*.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/${{ env.BUILD_PRESET_NAME }}/vcpkg-manifest-install.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/release/**/*.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/release/vcpkg-manifest-install.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/debug/**/*.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/Build/debug/vcpkg-manifest-install.log
            ${{ env.LADYBIRD_CHECKOUT_DIR }}/**/*.log
          if-no-files-found: ignore
          retention-days: 7