name: Build Ladybird Browser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: LadybirdBrowser/ladybird
        submodules: 'recursive' # 如果您的项目包含子模块，请保留此行

    - name: Install Dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          autoconf-archive \
          automake \
          build-essential \
          ccache \
          cmake \
          curl \
          fonts-liberation2 \
          git \
          libgl1-mesa-dev \
          nasm \
          ninja-build \
          pkg-config \
          qt6-base-dev \
          qt6-tools-dev-tools \
          qt6-wayland \
          tar \
          unzip \
          zip \
          libpulse-dev
        # 从 Kitware APT 仓库安装 CMake 3.25+
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/kitware.list
        sudo apt-get update
        sudo apt-get install -y cmake
        # 安装支持 C++23 的 Clang 编译器
        sudo wget -O /usr/share/keyrings/llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
        echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg.key] https://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-19 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list
        sudo apt-get update
        sudo apt-get install -y clang-19 lld-19

    - name: Build Ladybird (Linux)
      env:
        CC: clang-19
        CXX: clang++-19
      run: |
        ./Meta/ladybird.sh build

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: LadybirdBrowser/ladybird
        submodules: 'recursive' # 如果您的项目包含子模块，请保留此行

    - name: Install Dependencies (macOS)
      run: |
        brew install \
          autoconf \
          autoconf-archive \
          automake \
          ccache \
          cmake \
          nasm \
          ninja \
          pkg-config \
          qt6 # 为 Qt UI 安装 qt6 (详情请参阅 BuildInstructionsLadybird.md)；如果仅构建 AppKit 版本则可省略
        # 注意：如果默认的 Xcode Clang 版本不足，可能需要取消注释下一行并安装特定版本的 llvm
        # brew install llvm@19

    - name: Build Ladybird (macOS)
      # 注意：如果默认的 Xcode Clang 版本不足，可能需要设置 CC 和 CXX 指向 Homebrew 安装的 Clang
      # env:
      #   CC: $(brew --prefix llvm@19)/bin/clang
      #   CXX: $(brew --prefix llvm@19)/bin/clang++
      run: |
        ./Meta/ladybird.sh build